{% set name = "MintPy" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/insarlab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6c1242dee74f13b96aa4b1f8d50c45ec486397796e4bd4bf3f67849f921bfe7f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - cartopy
    - cvxopt
    - dask >=1.0
    - dask-jobqueue >=0.3
    - defusedxml
    - h5py <3
    - joblib
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - pyproj
    - scikit-image
    - scipy
    - pykml >=0.2
    - pysolid
    - pyaps3
    - gdal >=3
    - pyresample
    - openmp
    - pykdtree
    - xarray
    - zarr

test:
  imports:
    - mintpy
  commands:
    - smallbaselineApp.py --help
    - view.py --help
    - tsview.py --help
    - info.py --help

about:
  home: https://github.com/insarlab/mintpy
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Miami INsar Time-series software in PYthon
  description: |
    The Miami INsar Time-series software in PYthon (MintPy as /mɪnt paɪ/) is an
    open-source package for Interferometric Synthetic Aperture Radar (InSAR)
    time series analysis. It reads the stack of interferograms (coregistered and
    unwrapped) in ISCE, ARIA, FRInGE, HyP3, GMTSAR, SNAP, GAMMA or ROI_PAC format,
    and produces three dimensional (2D in space and 1D in time) ground surface
    displacement in line-of-sight direction. It includes a routine time series
    analysis (smallbaselineApp.py) and some independent toolbox.
  doc_url: https://mintpy.readthedocs.io
  dev_url: https://github.com/insarlab/mintpy

extra:
  recipe-maintainers:
    - jhkennedy
    - jlrine2
    - yunjunz
